import type { Metadata } from "next";
import "./globals.css";
import { Alice } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const alice = Alice({
  subsets: ['latin'],
  weight: ['400'], // Add other weights if needed, e.g., ['400', '700']
  variable: '--font-alice', // Define a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alice.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
